_wandb:
    value:
        cli_version: 0.23.0
        e:
            bjkanoyn2xjcbsn3as95ky6w1vq7k7wm:
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 16
                cpu_count_logical: 24
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "999321694208"
                        used: "905268187136"
                email: 22000245@handong.ac.kr
                executable: C:\ProgramData\anaconda3\envs\trm-unet\python.exe
                git:
                    commit: 7811bbcc385f52d750e4cccde859a8970b60b57a
                    remote: https://github.com/ssidnwm/Tiny-RecUNet.git
                gpu: NVIDIA RTX A5000
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 8192
                      memoryTotal: "25757220864"
                      name: NVIDIA RTX A5000
                      uuid: GPU-369ae43e-74e8-e3a8-d15a-f37ccf13aa1b
                    - architecture: Ampere
                      cudaCores: 8192
                      memoryTotal: "25757220864"
                      name: NVIDIA RTX A5000
                      uuid: GPU-bba941b2-fbe3-6432-7f77-6da7af989b7c
                host: T_lab_01
                memory:
                    total: "68497039360"
                os: Windows-10-10.0.22631-SP0
                program: main.py
                python: CPython 3.8.19
                root: C:\Users\82109\Desktop\벼리\7학기\ai융합과 응용\Tiny-RecUnet\Tiny-RecUNet
                startedAt: "2025-11-21T13:50:18.845188Z"
                writerId: bjkanoyn2xjcbsn3as95ky6w1vq7k7wm
        m: []
        python_version: 3.8.19
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
                - 15
            "4": 3.8.19
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
