_wandb:
    value:
        cli_version: 0.23.0
        e:
            1kmwmxi4hx3xrt0wo7w5jsa82y4my2w0:
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 16
                cpu_count_logical: 24
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "999321694208"
                        used: "911625465856"
                email: 22000245@handong.ac.kr
                executable: C:\ProgramData\anaconda3\envs\trm-unet\python.exe
                git:
                    commit: 7811bbcc385f52d750e4cccde859a8970b60b57a
                    remote: https://github.com/ssidnwm/Tiny-RecUNet.git
                gpu: NVIDIA RTX A5000
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 8192
                      memoryTotal: "25757220864"
                      name: NVIDIA RTX A5000
                      uuid: GPU-369ae43e-74e8-e3a8-d15a-f37ccf13aa1b
                    - architecture: Ampere
                      cudaCores: 8192
                      memoryTotal: "25757220864"
                      name: NVIDIA RTX A5000
                      uuid: GPU-bba941b2-fbe3-6432-7f77-6da7af989b7c
                host: T_lab_01
                memory:
                    total: "68497039360"
                os: Windows-10-10.0.22631-SP0
                program: main.py
                python: CPython 3.8.19
                root: C:\Users\82109\Desktop\벼리\7학기\ai융합과 응용\Tiny-RecUnet\Tiny-RecUNet
                startedAt: "2025-11-25T07:04:43.478656Z"
                writerId: 1kmwmxi4hx3xrt0wo7w5jsa82y4my2w0
        m:
            - "1": epoch
              "6":
                - 3
              "7": []
            - "1": train_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": val_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": val_dsc
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.8.19
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 7
                - 13
                - 15
                - 61
            "4": 3.8.19
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
aug_angle:
    value: 15
aug_scale:
    value: 0.05
batch_size:
    value: 8
epochs:
    value: 50
image_size:
    value: 224
lr:
    value: 0.00015084515574125297
model_args:
    value:
        backbone: resnet34
        decoder_channels:
            - 256
            - 128
            - 64
            - 16
        depth: 6
        embed_dim: 128
        embed_dropout: 0.08336140250149256
        head_channels: 256
        img_size: 224
        in_channels: 3
        mlp_ratio: 4
        num_heads: 8
        out_channels: 1
        patch_grid: null
        pretrained_backbone: false
model_name:
    value: TransUnet
overrides:
    value:
        batch_size: 8
        decoder_channels: 256,128,64,16
        depth: 6
        embed_dim: 128
        embed_dropout: 0.08336140250149256
        head_channels: 256
        lr: 0.00015084515574125297
        num_heads: 8
        patch_grid: None
param_count:
    value: 11880193
workers:
    value: 4
